### ISSUE TITLE
NPM ReadME out of date

### ISSUE THREAD

**Issue by flowhamster** [BlockScore/blockscore-node#17]
API docs for scoring a question set are out of date:
View Readme here: https://www.npmjs.com/package/blockscore

It says:
```
var data = {
    person_id: response.person_id,
    question_set_id: response.id,
    answers: [
      {
        question_id: 1,
        answer_id: 1
```

It should be
```
var data = {
    id: question_set.id,
    answers: [
      {
        question_id: 1,
        answer_id: 1
```

**Comment by backus** [comment]
Thanks for letting us know, Kevin! I'll try to get this fixed.  In the meantime, our [hosted docs](http://docs.blockscore.com/v4.0/node/) are more regularly kept up to date.

**Comment by backus** [comment]
@kingkevin I'm pretty sure it is updated now. However, npmjs.com is serving me different READMEs depending on the page load.  Can you confirm it is updated?
