### ISSUE TITLE
question_sets.create cannot set time_limit

### ISSUE THREAD

**Issue by saroman082** [BlockScore/blockscore-node#22]
I am unable to set a time_limit when creating a question set.  This is defined as an optional argument in the API docs but does not seem to exist as an option in the implementation.

**Comment by saroman082** [comment]
Rechecked and seems it does consider the timeout in the

**Comment by saroman082** [comment]
My mistake.  Should have passed as person_id.

**Comment by alainmeier** [comment]
No worries, glad it works for you. Let us know if you need any additional help.
