### ISSUE TITLE
Request body with non ASCII characters is rejected

### ISSUE THREAD

**Issue by DenisStad** [BlockScore/blockscore-node#32]
When I tried to submit user info with non ASCII characters, in my specific instance it was a `ß` which is very common in German street names, the request was rejected with the error message `invalid_request_error: Poorly formed JSON request body.`.

The problem is that the stringified JSON body has a different content length than passed in the request when non ASCII characters are present. A fix for this problem was done by someone else here:
https://github.com/sentientwaffle/blockscore-node/commit/61fa874e41c5dc154145205aad8c79e41bbe8940

This is a critical issue since Blockscore is targeted to non US citizens, too, and with this issue it's not possible to enter characters that are common in other languages.

**Comment by dgollahon** [comment]
Hi @DenisStad are you using the latest version of `blockscore-node`? I believe the content length issue you're referring to (#25) was resolved in #30 and released in version `4.0.3`.

If you are using `4.0.3` and you still have this issue, could you add a small, executable code sample that reproduces the bug?

Thanks!

**Comment by DenisStad** [comment]
Oh, I was indeed on 4.0.2. Sorry to bother!
